Console.Clear();
Console.Write("Write number k1: ");
double k1 = Convert.ToDouble(Console.ReadLine());
Console.Write("Write number b1: ");
double b1 = Convert.ToDouble(Console.ReadLine());
Console.Write("Write number k2: ");
double k2 = Convert.ToDouble(Console.ReadLine());
Console.Write("Write number b2: ");
double b2 = Convert.ToDouble(Console.ReadLine());
double x = (b2 - b1) / (k1 - k2);
double y = k1 * x + b1;
Console.WriteLine($"Result: ({x}, {y})");